config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'categories#index'

  authenticated :user do
      resources :categories, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :expenses
      resources :splash
  end
    get 'users/sign_in' => 'devise/sessions#new'
    get '/categories', to: 'categories#index'
    get '/transactions', to: 'expenses#index'
end

app/controllers/category_expenses_controller.rb
class CategoryExpensesController < ApplicationController
  before_action :authenticate_user!

  # GET /category_expenses or /category_expenses.json
  def index
    @category_expenses = CategoryExpense.all
  end

  # GET /category_expenses/1 or /category_expenses/1.json
  def show
  end

  # GET /category_expenses/new
  def new
    @category_expense = CategoryExpense.new
  end

  # GET /category_expenses/1/edit
  def edit
  end

  # POST /category_expenses or /category_expenses.json
  def create
    @category_expense = CategoryExpense.new(category_expense_params)

    respond_to do |format|
      if @category_expense.save
        format.html { redirect_to category_expense_url(@category_expense), notice: "Category expense was successfully created." }
        format.json { render :show, status: :created, location: @category_expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_expenses/1 or /category_expenses/1.json
  def update
    respond_to do |format|
      if @category_expense.update(category_expense_params)
        format.html { redirect_to category_expense_url(@category_expense), notice: "Category expense was successfully updated." }
        format.json { render :show, status: :ok, location: @category_expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_expenses/1 or /category_expenses/1.json
  def destroy
    @category_expense.destroy

    respond_to do |format|
      format.html { redirect_to category_expenses_url, notice: "Category expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_expense
      @category_expense = CategoryExpense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_expense_params
      params.require(:category_expense).permit(:category_id, :expense_id)
    end
end

app/helpers/category_expenses_helper.rb
module CategoryExpensesHelper
end

app/views/category_expenses/_category_expense.html.erb
<div id="<%= dom_id category_expense %>">
  <p>
    <strong>Category:</strong>
    <%= category_expense.category_id %>
  </p>

  <p>
    <strong>Expense:</strong>
    <%= category_expense.expense_id %>
  </p>

</div>

app/views/category_expenses/_form.html.erb
<%= form_with(model: category_expense) do |form| %>
  <% if category_expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category_expense.errors.count, "error") %> prohibited this category_expense from being saved:</h2>

      <ul>
        <% category_expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :expense_id, style: "display: block" %>
    <%= form.text_field :expense_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/category_expenses/edit.html.erb
<h1>Editing category expense</h1>

<%= render "form", category_expense: @category_expense %>

<br>

<div>
  <%= link_to "Show this category expense", @category_expense %> |
  <%= link_to "Back to category expenses", category_expenses_path %>
</div>

app/views/category_expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Category expenses</h1>

<div id="category_expenses">
  <% @category_expenses.each do |category_expense| %>
    <%= render category_expense %>
    <p>
      <%= link_to "Show this category expense", category_expense %>
    </p>
  <% end %>
</div>

<%= link_to "New category expense", new_category_expense_path %>

app/views/category_expenses/new.html.erb
<h1>New category expense</h1>

<%= render "form", category_expense: @category_expense %>

<br>

<div>
  <%= link_to "Back to category expenses", category_expenses_path %>
</div>

app/views/category_expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category_expense %>

<div>
  <%= link_to "Edit this category expense", edit_category_expense_path(@category_expense) %> |
  <%= link_to "Back to category expenses", category_expenses_path %>

  <%= button_to "Destroy this category expense", @category_expense, method: :delete %>
</div>